//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на auth.
        /// </summary>
        public static string AuthDataPath {
            get {
                return ResourceManager.GetString("AuthDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на config.ini.
        /// </summary>
        public static string ConfigFilePath {
            get {
                return ResourceManager.GetString("ConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на zdata.
        /// </summary>
        public static string DataPath {
            get {
                return ResourceManager.GetString("DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требования для имени:
        ///минимум 1 символ
        ///максимум 32 символа.
        /// </summary>
        public static string DisplayNameRequiredString {
            get {
                return ResourceManager.GetString("DisplayNameRequiredString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zireael Downloads.
        /// </summary>
        public static string DownloadPath {
            get {
                return ResourceManager.GetString("DownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пример:
        ///example@gmail.com.
        /// </summary>
        public static string EmailRequiredString {
            get {
                return ResourceManager.GetString("EmailRequiredString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на images\group.
        /// </summary>
        public static string GroupImagePath {
            get {
                return ResourceManager.GetString("GroupImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требования для логина:
        ///может состоять только из латинских символов и цифр
        ///минимум 6 символов
        ///максимум 24 символа.
        /// </summary>
        public static string LoginRequiredString {
            get {
                return ResourceManager.GetString("LoginRequiredString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 262144.
        /// </summary>
        public static string PackageSize {
            get {
                return ResourceManager.GetString("PackageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требования для пароля:
        ///минимум 8 символов
        ///максимум 32 символа
        ///буква в нижнем регистре
        ///буква в верхнем регистре.
        /// </summary>
        public static string PasswordRequiredString {
            get {
                return ResourceManager.GetString("PasswordRequiredString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ^.{1,32}$.
        /// </summary>
        public static string RegexDisplayNamePattern {
            get {
                return ResourceManager.GetString("RegexDisplayNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ^\w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$.
        /// </summary>
        public static string RegexEmailPattern {
            get {
                return ResourceManager.GetString("RegexEmailPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ^(?=.*[A-Za-z0-9]$)[A-Za-z][A-Za-z\d]{5,24}$.
        /// </summary>
        public static string RegexLoginPattern {
            get {
                return ResourceManager.GetString("RegexLoginPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ^(?=.*[a-zа-я])(?=.*[A-ZА-Я]).{8,32}$.
        /// </summary>
        public static string RegexPasswordPattern {
            get {
                return ResourceManager.GetString("RegexPasswordPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на zpdg7okZ5x0E8ibMHGoboiXieesoCi8w5dhi4ZU6CIUPEIP1X5onKtMSyMtb61xI.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на savedfiles.
        /// </summary>
        public static string SavedFileSerializeFileName {
            get {
                return ResourceManager.GetString("SavedFileSerializeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на images.
        /// </summary>
        public static string UserImagesPath {
            get {
                return ResourceManager.GetString("UserImagesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на usertag.
        /// </summary>
        public static string UsernamePath {
            get {
                return ResourceManager.GetString("UsernamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Zireael_logo_64 {
            get {
                object obj = ResourceManager.GetObject("Zireael_logo_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
