//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auth.
        /// </summary>
        public static string AuthDataPath {
            get {
                return ResourceManager.GetString("AuthDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.ini.
        /// </summary>
        public static string ConfigFilePath {
            get {
                return ResourceManager.GetString("ConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zdata.
        /// </summary>
        public static string DataPath {
            get {
                return ResourceManager.GetString("DataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требования для имени:
        ///минимум 1 символ
        ///максимум 32 символа.
        /// </summary>
        public static string DisplayNameRequiredString {
            get {
                return ResourceManager.GetString("DisplayNameRequiredString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zireael Downloads.
        /// </summary>
        public static string DownloadPath {
            get {
                return ResourceManager.GetString("DownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример:
        ///example@gmail.com.
        /// </summary>
        public static string EmailRequiredString {
            get {
                return ResourceManager.GetString("EmailRequiredString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images\group.
        /// </summary>
        public static string GroupImagePath {
            get {
                return ResourceManager.GetString("GroupImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требования для логина:
        ///только латинские символы и цифры
        ///минимум 6 символов
        ///максимум 24 символа.
        /// </summary>
        public static string LoginRequiredString {
            get {
                return ResourceManager.GetString("LoginRequiredString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 262144.
        /// </summary>
        public static string PackageSize {
            get {
                return ResourceManager.GetString("PackageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требования для пароля:
        ///минимум 8 символов
        ///максимум 32 символа
        ///буква в нижнем регистре
        ///буква в верхнем регистре.
        /// </summary>
        public static string PasswordRequiredString {
            get {
                return ResourceManager.GetString("PasswordRequiredString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^.{1,32}$.
        /// </summary>
        public static string RegexDisplayNamePattern {
            get {
                return ResourceManager.GetString("RegexDisplayNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$.
        /// </summary>
        public static string RegexEmailPattern {
            get {
                return ResourceManager.GetString("RegexEmailPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?=.*[A-Za-z0-9]$)[A-Za-z][A-Za-z\d]{5,24}$.
        /// </summary>
        public static string RegexLoginPattern {
            get {
                return ResourceManager.GetString("RegexLoginPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?=.*[a-zа-я])(?=.*[A-ZА-Я]).{8,32}$.
        /// </summary>
        public static string RegexPasswordPattern {
            get {
                return ResourceManager.GetString("RegexPasswordPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zpdg7okZ5x0E8ibMHGoboiXieesoCi8w5dhi4ZU6CIUPEIP1X5onKtMSyMtb61xI.
        /// </summary>
        public static string Salt {
            get {
                return ResourceManager.GetString("Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to savedfiles.
        /// </summary>
        public static string SavedFileSerializeFileName {
            get {
                return ResourceManager.GetString("SavedFileSerializeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images.
        /// </summary>
        public static string UserImagesPath {
            get {
                return ResourceManager.GetString("UserImagesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usertag.
        /// </summary>
        public static string UsernamePath {
            get {
                return ResourceManager.GetString("UsernamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Zireael_logo_64 {
            get {
                object obj = ResourceManager.GetObject("Zireael_logo_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
